// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    session_id, role, content, tool_type, tool_payload, image_path
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, session_id, role, content, tool_type, tool_payload, image_path, created_at
`

type CreateMessageParams struct {
	SessionID   pgtype.UUID `json:"session_id"`
	Role        string      `json:"role"`
	Content     string      `json:"content"`
	ToolType    pgtype.Text `json:"tool_type"`
	ToolPayload []byte      `json:"tool_payload"`
	ImagePath   pgtype.Text `json:"image_path"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolType,
		arg.ToolPayload,
		arg.ImagePath,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.ToolType,
		&i.ToolPayload,
		&i.ImagePath,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesBySession = `-- name: GetMessagesBySession :many
SELECT id, session_id, role, content, tool_type, tool_payload, image_path, created_at FROM messages WHERE session_id = $1 ORDER BY created_at ASC
`

func (q *Queries) GetMessagesBySession(ctx context.Context, sessionID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ToolType,
			&i.ToolPayload,
			&i.ImagePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
