// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID          pgtype.UUID        `json:"id"`
	SessionID   pgtype.UUID        `json:"session_id"`
	Role        string             `json:"role"`
	Content     string             `json:"content"`
	ToolType    pgtype.Text        `json:"tool_type"`
	ToolPayload []byte             `json:"tool_payload"`
	ImagePath   pgtype.Text        `json:"image_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
