// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (device_id) VALUES ($1) RETURNING id, device_id, title, created_at, updated_at
`

func (q *Queries) CreateSession(ctx context.Context, deviceID pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, deviceID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND device_id = $2
`

type DeleteSessionParams struct {
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.DeviceID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, device_id, title, created_at, updated_at FROM sessions WHERE id = $1 AND device_id = $2
`

type GetSessionParams struct {
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.DeviceID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByDevice = `-- name: ListSessionsByDevice :many
SELECT s.id, s.device_id, s.title, s.created_at, s.updated_at, COUNT(m.id) as message_count
FROM sessions s LEFT JOIN messages m ON s.id = m.session_id
WHERE s.device_id = $1
GROUP BY s.id
ORDER BY s.updated_at DESC
`

type ListSessionsByDeviceRow struct {
	ID           pgtype.UUID        `json:"id"`
	DeviceID     pgtype.UUID        `json:"device_id"`
	Title        string             `json:"title"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	MessageCount int64              `json:"message_count"`
}

func (q *Queries) ListSessionsByDevice(ctx context.Context, deviceID pgtype.UUID) ([]ListSessionsByDeviceRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByDeviceRow
	for rows.Next() {
		var i ListSessionsByDeviceRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionTitle = `-- name: UpdateSessionTitle :one
UPDATE sessions SET title = $1, updated_at = NOW()
WHERE id = $2 AND device_id = $3 RETURNING id, device_id, title, created_at, updated_at
`

type UpdateSessionTitleParams struct {
	Title    string      `json:"title"`
	ID       pgtype.UUID `json:"id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) UpdateSessionTitle(ctx context.Context, arg UpdateSessionTitleParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionTitle, arg.Title, arg.ID, arg.DeviceID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
